# site name
prefixName: 
siteName: SLAKIJNG's WORLD
# favicon and site master avatar
favicon: /images/favicon.ico
avatar: assets/img/common/avatar.jpg
url: 
description: TIME IS NOT YOUR ENEMY. FOREVER IS.
cdn: 
pjax: 1
# 1开启
mathjax: 0

notice: 广告位招租
lazyloadImg: 

menus:
  首页: { path: /, fa: fa-fort-awesome faa-shake }
  作品集: { path: /categories/Portfolio/, fa: fa-photo }
  文章: { path: /categories/Article/, fa: fa-book }
  歌单: { path: /music/, fa: fa-headphones }
  # 关于: {path: /about/, fa: fa-meetup}


# Home page sort type: -1: newer first，1: older first.
homePageSortType: -1
# Home page article shown number)
homeArticleShown: 10
# 背景图片 更好的修改
bg:
- assets/img/common/background_bloodborne.jpeg

# 背景图片样式 空 原图效果 filter-dim 阴影 filter-grid 横条 filter-dot 点点
bgclass: filter-dot

# startdash url, title, desc img
startdash: 
  - {url: /2020/04/22/2020-4-22-Ecolocation/, title: Echolocation, img: /assets/img/common/echolocation_0.gif}
  - {url: /2019/02/10/2019-2-10-On-The-Way-Home/, title: On the Way Home, img: /assets/img/common/On_the_way_home_0.gif}
  - {url: /2021/08/06/2021-8-6-Narrative-Approach-of-Dark-Souls/, title: 黑暗之魂叙事的取舍, img: /assets/img/common/darksousl2_faraamknight.jpg}



# your site build time or founded date
siteBuildingTime: 07/17/2018

#social  url, img PC端配置
social:
   github: {url: https://github.com/Antastsy7, img: /assets/img/common/github.png}
#   wangyiyun: {url: https://music.163.com/, img: /img/social/wangyiyun.png}
#   zhihu: {url: https://www.zhihu.com/, img: /img/social/zhihu.png}
#   qq: {url: /#, qrcode: /img/custom/qq.png, img: /img/social/qq.png}
#   wechat: {url: /#, qrcode: /img/custom/wechat.png, img: /img/social/wechat.png}

#social  url, img 移动端配置
msocial:
  github: {url: https://github.com/Antastsy7, fa: fa-github, color: 333}
  weibo: {url: http://weibo.com/mashirozx?is_all=1, fa: fa-weibo, color: dd4b39}
  qq: {url: https://wpa.qq.com/msgrd?v=3&uin=954655431&site=qq&menu=yes, fa: fa-qq, color: 25c6fe}

donate:
  paypal:
  alipay: 
  wechat: 
  wechatSQ: 

# 视频地址为https://cdn.jsdelivr.net/gh/honjun/hojun@1.2/Unbroken.mp4，配置如下
movies:
  url: 
  # 多个视频用逗号隔开，随机获取。支持的格式目前已知MP4,Flv。其他的可以试下，不保证有用
  name: 

aplayer: 
  id: 
  server: netease
  type: playlist
  fixed: true
  autoplay: false
  loop: all
  order: random
  preload: auto
  volume: 0.7
  mutex: true

# Valine
valine: true
v_appId: GyC3NzMvd0hT9Yyd2hYIC0MN-gzGzoHsz
v_appKey: mgOpfzbkHYqU92CV4IDlAUHQ

